version: "3"
services:
  rasa:
    image: sumand/rasa-server:3.5.2
    container_name: rasa-server
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks: ["rasa-network"]
    ports:
      - "5005:5005"
    volumes:
      - "./:/app"
    command:
      - run
      - --cors
      - "*"
      - --enable-api
    depends_on:
      - action-server
  action-server:
    container_name: rasa-action-server
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: sumand/rasa-action-server:3.5.1
    networks: ["rasa-network"]
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"
networks: { rasa-network: {} }